### ISSUE TITLE
Ability to process only a single image or set of images

### ISSUE THREAD

**Issue by strugee** [matiasdelellis/facerecognition#245] opened 2020-03-31 20:56 UTC
(Deleting the issue template since this is a feature request - I'm on version 0.5.14 of the app.)

It would be helpful to be able to specify a path to a single image or a set of a few (on the order of 5 or 10, all specified on the command line) to process. The tool would process these images and immediately terminate, which would help the administrator tune the settings.

Essentially the workflow I'm imagining is:

1. The admin picks a set of interesting images that they know have some faces in them.
2. The admin runs the tool with only those images.
3. Based on the clustering, number of faces recognized etc., the admin goes back and tunes the settings further.
4. Repeat from step 2 until the settings are optimal.

Right now the alternative is just to spot-check filenames as they go by in the console, which is unideal for a couple reasons (it's cumbersome, hard to pick known-interesting images, the crawl process after a reset is slow, etc.).

**Comment by matiasdelellis** [comment] 2020-03-31 21:10
Hi @strugee 

Thanks for the idea, but I guess we can take it as a duplicate of https://github.com/matiasdelellis/facerecognition/issues/91 :wink: 

However for testing I suggest you create a new user, and upload a couple of photos directly there. I in particular do that. I have a user called 'test' and another 'user' where I have some photos of Big Bang Theory to test. :wink: 

p.s: If I had done that testing yesterday, I would have discovered your latest bug before publish.. haha.. :sweat_smile:

**Comment by strugee** [comment] 2020-04-01 01:20
Not quite a duplicate of #91 since single files are more useful for huge folders like `InstantUpload`... it's easy enough to copy images to a dedicated test directory though so feel free to close this as a duplicate; it might just not be worth doing this one since the workaround is so easy. The secondary user is a good idea though. I wonder if it'd be worth adding to the README as a suggestion for admins.

I'm also wondering if you'd be willing to share your set of Big Bang Theory images with me, either on GitHub or via the email in my profile? I've been wanting to do some tests on Google Photos to see how the UX compares to what could be done in Nextcloud Photos but I don't want to upload any of my own images.

**Comment by matiasdelellis** [comment] 2020-04-01 13:56
> Not quite a duplicate of #91 since single files are more useful for huge folders like InstantUpload... it's easy enough to copy images to a dedicated test directory though so feel free to close this as a duplicate

But the way to implement it is exactly the same.. Even more, that only work with folders, it would be a restriction to the same code. :sweat_smile: 
Now I extend this, so that it also describes this.. :wink: 

> The secondary user is a good idea though. I wonder if it'd be worth adding to the README as a suggestion for admins.

Maybe, but the Readme should give a minimal view of the functions. In any case we should write a wiki really step by step on how to install and test it.

> Since you mentioned it I'm also wondering if you'd be willing to share your set of Big Bang Theory images with me, either on GitHub or via the email in my profile? I've been wanting to do some tests on Google Photos to see how the UX compares to what could be done in Nextcloud Photos but I don't want to upload any of my own images.

It has nothing special, are photos that I download from google. There are some duplicate photos and also small photos that are ignored, but I guess it is similar to personal photos.

https://services.delellis.com.ar/data/The%20Big%20Bang%20Theory.zip

The big difference is that you can see several groups of the same person here, but you will see that the main group is very similar to google photos.

**Comment by strugee** [comment] 2020-04-02 00:19
> https://services.delellis.com.ar/data/The%20Big%20Bang%20Theory.zip

This is 403 Forbidden for me. The rest makes sense though :)

I can try to write a wiki page on tuning if I find some time soon.

**Comment by matiasdelellis** [comment] 2020-04-02 00:50
> This is 403 Forbidden for me. The rest makes sense though :)

Ohh.. Fixed..
Then tell me how the test went .. 😉 

> I can try to write a wiki page on tuning if I find some time soon.

Ok .. When you can, always welcome.. 😄

**Comment by matiasdelellis** [comment] 2020-04-10 17:31
Close in favor of #91 
:wink:

**Closed by matiasdelellis** 2020-04-10 17:31 UTC
