### ISSUE TITLE
Setup doesn't work on objectstore

### ISSUE THREAD

**Issue by hahagu** [matiasdelellis/facerecognition#381] opened 2020-11-17 15:50 UTC
### Expected behaviour

Model 1 should download when running the code

`occ face:setup -m 1`

### Actual behaviour

Error is produced:

`The model 1 (Default) will be installed

In FileService.php line 366:

  The file public_html/data/appdata_{random_string_here}/facerecognition/models/1/mmod_human_face_detector.dat exists or is not writable`

### Server Configuration

Object storage is configured as primary storage, using the [official guide](https://docs.nextcloud.com/server/15/admin_manual/configuration_files/primary_storage.html).

All other requirements are fulfilled, such as DLib and PDLib.

**Comment by hahagu** [comment] 2020-11-17 15:53
The error also seems to be a typo.

exists -> does not exist

**Comment by matiasdelellis** [comment] 2020-11-17 19:28
Hi @hahagu 
It seems a valid error considering that I never tried a similar configuration. :disappointed: 
Soon I will try to investigate it.. 

Thanks for report it..

**Comment by hahagu** [comment] 2020-11-20 09:37
> Hi @hahagu
> It seems a valid error considering that I never tried a similar configuration. 😞
> Soon I will try to investigate it..
> 
> Thanks for report it..

A quick fix would be downloading the models to the app directory itself, instead of the app directory, since the app is always locally stored.

**Comment by matiasdelellis** [comment] 2020-11-20 14:01
> A quick fix would be downloading the models to the app directory itself, instead of the app directory, since the app is always locally stored.

Before when we had only one model, it worked like that, but change it because of the big size of tarball. Now that we have several models, and are installable by user, if we write in the application folder, the folder checksum changes and the application would be "invalid". 😞

**Comment by hahagu** [comment] 2020-11-21 13:02
If the models are not too big, it can ship with the app by default maybe?
Enable and disable modules to liking.

**Comment by matiasdelellis** [comment] 2020-11-21 13:23
NO..
When we had only one model this seemed viable. However, it was already too big for nextcloud  https://github.com/matiasdelellis/facerecognition/issues/1#issuecomment-557831399

Then they changed this limit, https://github.com/nextcloud/server/pull/19017 just to allow install documentserver app, but this causes a lot of timeout problems on nextcloud servers.

Going back bundle the models would be a regression, in any case, we have to find a new place to install them..

**Comment by matiasdelellis** [comment] 2020-11-21 13:41
p.s: If you want I can help you to make a patch to use momentarily but I will not accept it in any way officially. sorry..

This commit should already guide you a bit. 😉 
https://github.com/matiasdelellis/facerecognition/commit/83cd40f1eaf2fe50a6fb54519ec41cc2569bce94#diff-0f7a159e22d644f20018369aaa9bff04cf3bd37287cc47d644854a7232f2eba3

**Comment by hahagu** [comment] 2020-11-23 07:40
> p.s: If you want I can help you to make a patch to use momentarily but I will not accept it in any way officially. sorry..
> 
> This commit should already guide you a bit. 😉
> [83cd40f#diff-0f7a159e22d644f20018369aaa9bff04cf3bd37287cc47d644854a7232f2eba3](https://github.com/matiasdelellis/facerecognition/commit/83cd40f1eaf2fe50a6fb54519ec41cc2569bce94#diff-0f7a159e22d644f20018369aaa9bff04cf3bd37287cc47d644854a7232f2eba3)

Another proposal for the solution:
Use the [AppData](https://docs.nextcloud.com/server/20/developer_manual/basics/storage/appdata.html) filesystem.

**Comment by matiasdelellis** [comment] 2020-11-23 12:28
Oh.. Seem an valid place.. and switching to him should be easy.

**Comment by matiasdelellis** [comment] 2020-11-23 23:03
Hi @hahagu 
I just realized that the new [external model](https://github.com/matiasdelellis/facerecognition/pull/389) can also help you .. :sweat_smile: 

If you wan to test, just replace your facerecognition folder with [that](https://github.com/matiasdelellis/facerecognition/pull/389#issuecomment-732457637), and follow the instructions of https://github.com/matiasdelellis/facerecognition-external-model

It should be easy.. :grimacing:

**Comment by hahagu** [comment] 2020-11-25 11:45
> Hi @hahagu
> I just realized that the new [external model](https://github.com/matiasdelellis/facerecognition/pull/389) can also help you .. 😅
> 
> If you wan to test, just replace your facerecognition folder with [that](https://github.com/matiasdelellis/facerecognition/pull/389#issuecomment-732457637), and follow the instructions of https://github.com/matiasdelellis/facerecognition-external-model
> 
> It should be easy.. 😬

Sorry for the slow response.
Yes, this can solve my problem, though I would need to do some configuring on my local nginx configuration.
However, not to be too invasive, wouldn't it be better for the application to fit the design spec on the official documentation and use the AppData filesystem library?
I believe that this would solve my problem, as well as not cause any permission issues, and guarantee support for future nextcloud versions.

**Comment by matiasdelellis** [comment] 2020-11-25 12:10
Hi @hahagu 

> Yes, this can solve my problem, though I would need to do some configuring on my local nginx configuration.
However, not to be too invasive, wouldn't it be better for the application to fit the design spec on the official documentation and use the AppData filesystem library?

That model was not written for this. But in this particular case it can help you. :sweat_smile: 

I investigated it and we are really already using AppData.. The problem is that to open the model, Pdlib needs direct access to the file, and need the full path to the file.
So, If Nextcloud saves this outside of your filesystem, it is not accessible. :disappointed: 

In any case, we need another place.

**Comment by hahagu** [comment] 2020-11-25 12:22
Oof.. that is an issue..
An idea:
How about making it so that you can configure the directory of models manually, but have it default to the appdata directory?
It can even exist outside the nextcloud directory if it's implemented this way.
I don't think that you'll need help to implement this, but I am always glad to.

**Comment by matiasdelellis** [comment] 2020-11-25 12:30
> How about making it so that you can configure the directory of models manually, but have it default to the appdata directory?
> It can even exist outside the nextcloud directory if it's implemented this way.

Great .. It seems like a good solution.. :grimacing: 

> I don't think that you'll need help to implement this, but I am always glad to.

If you dare, it is always welcome. :smile: :wink:

**Comment by hahagu** [comment] 2020-11-25 12:33
> > How about making it so that you can configure the directory of models manually, but have it default to the appdata directory?
> > It can even exist outside the nextcloud directory if it's implemented this way.
> 
> Great .. It seems like a good solution.. 😬
> 
> > I don't think that you'll need help to implement this, but I am always glad to.
> 
> If you dare, it is always welcome. 😄 😉

Haven't really had experience developing nextcloud applications, but it seems similar enough to laravel.
Eh, I can give it a go, but you might need to teach me some things 😋

**Comment by matiasdelellis** [comment] 2020-11-25 12:48
You just need something like this ...

* https://github.com/matiasdelellis/facerecognition/pull/389/commits/8e4e5501bda506cc309b7e448141969f29ef92c2

Add SettingsService here (with the previous statements of course)
* https://github.com/matiasdelellis/facerecognition/blob/master/lib/Service/ModelService.php#L50

Adjust this according to the new setting...
* https://github.com/matiasdelellis/facerecognition/blob/master/lib/Service/ModelService.php#L80-L97

And finally, move this to some private function that also take into account the new setting.. 
* https://github.com/matiasdelellis/facerecognition/blob/master/lib/Service/ModelService.php#L55-L60

:wink:

**Comment by hahagu** [comment] 2020-11-25 13:25
https://github.com/matiasdelellis/facerecognition/pull/390
This should do the trick?

**Comment by matiasdelellis** [comment] 2020-11-25 13:43
Wow..
Thanks for your first contribution.. :grimacing: :smile: 

It is going well, there I added some comments.. :wink:

**Comment by hahagu** [comment] 2020-11-25 14:24
I've updated the fork with the suggested updates. 😀

**Comment by matiasdelellis** [comment] 2020-11-25 14:27
More comments there, we misunderstood the comments.. :disappointed:

**Comment by hahagu** [comment] 2020-11-25 14:42
Fixed misunderstandings 👍

**Comment by matiasdelellis** [comment] 2020-11-25 20:49
Hi @hahagu 
Sorry .. Close your PR and commit one that works .. https://github.com/matiasdelellis/facerecognition/pull/391

:disappointed:

**Comment by matiasdelellis** [comment] 2020-11-26 13:40
Ok.. Merged..
Surely the weekend a minor version with this that..

**Closed** 2021-01-15 15:15 UTC
