### ISSUE TITLE
[Feature request] Ability to merge groups of faces together

### ISSUE THREAD

**Issue by aeltawela** [matiasdelellis/facerecognition#333] opened 2020-09-03 10:36 UTC
**This is a feature request**

It would be nice if there is an ability for the user to merge two groups of faces together if the user found they are for the same person. It will be perfect.

**Comment by NeroBurner** [comment] 2020-09-03 12:03
duplicate of: https://github.com/matiasdelellis/facerecognition/issues/134

**Comment by matiasdelellis** [comment] 2020-09-03 12:55
Yes,, 
Maybe it still takes a while to implement it, but I have already been thinking about how to implement it. 😄 

Thank @aeltawela @NeroBurner 
Close in flavour of #134

**Closed by matiasdelellis** 2020-09-03 12:55 UTC
