### ISSUE TITLE
`occ face:setup -m 3` doesn't indicate what deps are missing

### ISSUE THREAD

**Issue by strugee** [matiasdelellis/facerecognition#244] opened 2020-03-31 02:31 UTC
Note: omitted irrelevant sections of the issue template, like client configuration.

### Expected behaviour

When I run `occ face:setup -m 3` and receive an error about missing dependencies, I should be told what exactly is missing.

### Actual behaviour

I'm presented this with this generic error:

    % sudo -u www-data php -f /srv/http/nextcloud/occ face:setup -m 3
   You do not meet the dependencies to install the model 3 (DlibHog)

### Steps to reproduce

N/A basically

### Server configuration

* **Operating system:** Debian 10

* **Pdlib version:** 1.0

* **How is DLib installed:** from source (`make php-test` in the compatibility tool crashes with `std::bad_alloc`, presumably because I don't have enough memory, but I know it's installed okay because facial recognition has successfully run in the past - I just had to pass a parameter to `php` to jack up the memory limit)

* **How is PDlib installed:** from source: (the SaltStack equivalent of) `phpize && ./configure --prefix=/usr/local --enable-debug && make && sudo make install`

* **PHP version:** 7.3.14-1~deb10u1

* **Web server:** Apache 2

* **Database:** MySQL

* **Nextbutt version:** 18.0.3

#### Background task log with debug.

N/A

#### Web server error log

Nothing relevant.

#### Nextcloud log (data/nextcloud.log)

Nothing related is logged to the Nextcloud log.

**Comment by matiasdelellis** [comment] 2020-03-31 03:04
Hi,
Thank you for the report!. You are right, I must improve the messages .. :wink: 

Well, I understand that you had the application working, and you want to change to HOG for memory usage. No?.
The problem is that this model depends on a pdlib library that has not been released yet. :disappointed:

See: https://github.com/goodspb/pdlib/pull/20

We are seriously considering taking maintenance of this library, but in the meantime you should compile pdlib again from https://github.com/matiasdelellis/pdlib/tree/improve-hog

Sorry..

**Comment by strugee** [comment] 2020-03-31 04:26
No, don't apologize! Thank you so much for maintaining this application, I think it has a ton of potential :-)

I'll pin my SaltStack formulas to the tip of that branch and see if that fixes things. I'll also add a note to the wiki to that effect.

Thanks for the quick reply!

**Comment by strugee** [comment] 2020-04-01 00:09
Worked perfectly, and I see you've actually already edited the wiki. Thanks again :-)

I'll leave this ticket open for better error messages.

**Comment by stalker314314** [comment] 2020-04-09 22:16
I got bitten by this too:) Luckily, I remembered some issue like this and went searching in issues:) I tihnk either hide "HOG" model until that guy merges it, or let's just change docs to point to your fork?

**Comment by matiasdelellis** [comment] 2020-04-09 22:23
>  Minimal fix would be to say that "installed pdlib version is older than required for HOG model to work" (but that would be a lie, in a way:)

You should try the misc-fixes branch. Now I merge it. :wink: 

On the other hand, I was going to send you an email, but I summarize, I sent an email to goodspb, requesting permission for the maintenance of the library[1], and he never answered me, nor did it merge it.

[1]. That I warned you a year ago that we were sure to end up maintaining it. hahaha.. :sweat_smile: :disappointed: 
So, I'm going to keep a fork, and the idea is to make an organization for this application, and the library .. Ideas for name? just pdlib? facerecongnition?.

**Comment by matiasdelellis** [comment] 2020-04-09 22:24
> You should try the misc-fixes branch. Now I merge it. wink

It is not completely fixed, but the messages changed dramatically.

**Comment by matiasdelellis** [comment] 2020-04-10 16:31
Fixed on #254

**Closed by matiasdelellis** 2020-04-10 16:31 UTC
